# Generated by Django 3.0 on 2019-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
