# Generated by Django 3.0 on 2019-12-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20191211_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Time',
            field=models.DateField(),
        ),
    ]
