# Generated by Django 3.0 on 2019-12-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20191211_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
