# Generated by Django 3.0 on 2019-12-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Slug', models.CharField(max_length=200, unique=True)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('Time', models.DateField()),
            ],
        ),
    ]
