# Generated by Django 3.0 on 2019-12-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Sno',
        ),
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
