# Generated by Django 3.0 on 2019-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20191219_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Slug',
        ),
        migrations.AddField(
            model_name='post',
            name='Sno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
