# Generated by Django 3.0 on 2019-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20191219_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Time',
            field=models.DateField(auto_now=True),
        ),
    ]
